[package]
name = "catla_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = "3.19.0"
allocator-api2 = "0.3.0"
hashbrown = "0.15.4"
fxhash = "0.2.1"
regex = "1.11.1"
extension-fn = "1.2.0"
