[expected]
unnecessary = "この要素は不必要かもしれません"
statement = "ここには文を挿入することができます"
expression = "ここには式を挿入することができます"
import_elements = "ここではインポートする要素を指定することができます"
parenthesis_left = "'('が必要です"
parenthesis_right = "括弧を')'で閉じる必要があります"
brace_right = "括弧を'}'で閉じる必要があります"
variable_name = "'let'もしくは'var'の後には変数名が必要です"
function_name = "'function'の後には関数名が必要です"
function_argument = "ここでは関数の引数を定義することができます"
block = "ブロックが必要です"
data_struct_name = "データ型名もしくはインターフェース名が必要です"
extends_type = "拡張元となるデータ型を指定する必要があります"
implements_type = "実装するインターフェース型を指定する必要があります"
and_expression = "論理式もしくは計算式が必要です"
closure_argument = "ここではクロージャーの引数を定義することができます"
vertical_bar_right = "クロージャーの引数定義は'|'で閉じる必要があります"
fat_arrow = "クロージャーの引数定義の後には'=>'が必要です"
fat_arrow_and_block = "クロージャーの引数定義の後には'=>'と式またはブロックが必要です"
expression_or_block = "式もしくはブロックが必要です"
generics = "ここにはジェネリクスを記述することができます"
function_call = "ここには関数呼び出しが必要です"
if_statement_or_block = "if式もしくはブロックが必要です"
type_info = "型情報が必要です"

[advice]
message = "以下のように修正すると解決できるかもしれません"
add_label = "このように追記してみてください"
remove_label = "この要素を削除してみてください"
note = "この修正案が常に正しいとは限りません。行き詰まった場合にはドキュメントなどを参照してみてください"

[error.0001]
message = "文が区切られていません"
label_0 = "文を区切るには改行または';'を使用してください"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"
[error.0002]
message = "プログラムの記述形式が正しくありません"
label_0 = "この単語の並びが文法に則していません。"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"
[error.0003]
message = "入力が不足しています"
label_0 = "本来必要な要素が欠如しています。"
note = "恐らく前方の文が不完全です"
[error.0004]
message = "定義文の無い修飾子"
label_0 = "定義文が必要です。この後に変数定義、関数定義もしくはデータ型定義を記述する必要があります"
note = "定義文を書く必要のない場合は削除してみてください"
[error.0005]
message = "代入文の記述形式が正しくありません"
label_0 = "右側の記述形式が正しくありません。"
[error.0006]
message = "交換文の記述形式が正しくありません"
label_0 = "右側の記述形式が正しくありません。"
[error.0007]
message = "インポート文の記述形式が正しくありません"
label_0 = ""
[error.0008]
message = "変数定義の記述形式が正しくありません"
label_0 = ""
[error.0009]
message = "関数定義の記述形式が正しくありません"
label_0 = ""
[error.0010]
message = "データ型定義の記述形式が正しくありません"
label_0 = ""
[error.0011]
message = "drop文の記述形式が正しくありません"
label_0 = ""
[error.0012]
message = "ブロックの括弧が閉じられていません"
label_0 = ""
[error.0013]
message = "計算式または論理式の記述形式が正しくありません"
label_0 = "式として有効ではありません。"
[error.0014]
message = "クロージャーの記述形式が正しくありません"
label_0 = ""
[error.0015]
message = "関数呼び出しの記述形式が正しくありません"
label_0 = ""
[error.0016]
message = "new式の記述形式が正しくありません"
label_0 = ""
[error.0017]
message = "if式の記述形式が正しくありません"
label_0 = ""
[error.0018]
message = "loop式の記述形式が正しくありません"
label_0 = ""
[error.0019]
message = "マッピング演算子の記述形式が正しくありません"
label_0 = ""
[error.0020]
message = "型指定の記述形式が正しくありません"
label_0 = ""
[error.0021]
message = "ジェネリクスの記述形式が正しくありません"
label_0 = ""
[error.0022]
message = "同じ名称の要素がすでに定義されています"
label_0 = "この名称は重複しています"
label_1 = "ここで既に定義されています"
note = "関数や型の定義名を重複させることはできません"
[error.0023]
message = "定義されていない識別子です"
label_0 = "この識別子が定義されていません"
note = "変数、関数や型の名前（識別子）はこの場所よりも前方で定義されているものでなければ使用できません"
[error.0024]
message = "代入対象の記述形式が正しくありません"
label_0 = "代入対象として有効ではありません"
note = "変数やフィールドを指す内容の記述が必要です"
[error.0025]
message = "データ型定義のブロック内で使用できる文には制限があります"
label_0 = "この場所でこの文を記述することはできません"
note = "この場所には任意の処理を行う内容を直接記述することはできません。関数を使用してください"