[expected]
statement = "ここには文を挿入することができます"

[error.0001]
message = "文が区切られていません"
label_0 = "文を区切るには改行または';'を使用してください"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"
[error.0002]
message = "文法上正しくない単語の並びが検出されました"
label_0 = "この単語の並びが文法に則していません。"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"
[error.0003]
message = ""
label_0 = "この単語の並びが文法に則していません。"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"