[expected]
unnecessary = "この要素は不必要かもしれません"
statement = "ここには文を挿入することができます"
expression = "ここには式を挿入することができます"
import_elements = "ここではインポートする要素を指定することができます"
parenthesis_left = "ここには'('が必要です"
parenthesis_right = "ここには')'が必要です"
brace_right = "括弧を'}'で閉じる必要があります"
variable_name = "ここには変数名が必要です"
function_name = "ここには関数名が必要です"
function_argument = "ここでは関数の引数を定義することができます"
block = "ここにはブロックが必要です"

[error.0001]
message = "文が区切られていません"
label_0 = "文を区切るには改行または';'を使用してください"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"
[error.0002]
message = "文法上正しくない単語の並びが検出されました"
label_0 = "この単語の並びが文法に則していません。"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"
[error.0003]
message = "入力が不足しています"
label_0 = "本来必要な要素が欠如しています。"
note = "恐らく前方の文が不完全です"
[error.0004]
message = "定義文の無い修飾子"
label_0 = "定義文が必要です。この後に変数定義、関数定義もしくはデータ型定義を記述する必要があります"
note = "定義文を書く必要のない場合は削除してみてください"
[error.0005]
message = "インポート文の記述形式が正しくありません"
label_0 = "この単語の並びが文法に則していません。"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"