[expected]
unnecessary = "この要素は不必要かもしれません"
statement = "ここには文を挿入することができます"
expression = "ここには式を挿入することができます"
import_elements = "ここではインポートする要素を指定することができます"
parenthesis_left = "'('が必要です"
parenthesis_right = "括弧を')'で閉じる必要があります"
brace_right = "括弧を'}'で閉じる必要があります"
variable_name = "'let'もしくは'var'の後には変数名が必要です"
function_name = "'function'の後には関数名が必要です"
function_argument = "ここでは関数の引数を定義することができます"
block = "ブロックが必要です"
data_struct_name = "データ型名もしくはインターフェース名が必要です"
super_type_info = "実装するインターフェース型か継承するクラスを指定する必要があります"
and_expression = "論理式もしくは計算式が必要です"
closure_argument = "ここではクロージャーの引数を定義することができます"
vertical_bar_right = "クロージャーの引数定義は'|'で閉じる必要があります"
fat_arrow = "クロージャーの引数定義の後には'=>'が必要です"
fat_arrow_and_block = "クロージャーの引数定義の後には'=>'と式またはブロックが必要です"
expression_or_block = "式もしくはブロックが必要です"
generics = "ここにはジェネリクスを記述することができます"
function_call = "ここには関数呼び出しが必要です"
if_statement_or_block = "if式もしくはブロックが必要です"
type_info = "型情報が必要です"
greater_than = "括弧を'>'で閉じる必要があります"
field_assign = "フィールドの初期化式が必要です"

[advice]
message = "以下のように修正すると解決できるかもしれません"
add_label = "このように追記してみてください"
remove_label = "この要素を削除してみてください"
replace_with_function_label = "代わりに関数を定義してその中に処理を記述することを検討してください"
note = "この修正案が常に正しいとは限りません。行き詰まった場合にはドキュメントなどを参照してみてください"

[name_resolved_kind]
import = "インポートされた型以外の要素"
function = "関数名"
variable = "変数名"
function_argument = "関数の引数名"
closure_argument = "クロージャーの引数名"
user_type = "型名"
generics = "ジェネリクス要素名"

[error.0001]
message = "文が区切られていません"
label_0 = "文を区切るには改行または';'を使用してください"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"
[error.0002]
message = "プログラムの記述形式が正しくありません"
label_0 = "この単語の並びが文法に則していません。"
note = "前方の文が不完全な場合にもこのエラーが発生することがあります"
[error.0003]
message = "入力が不足しています"
label_0 = "本来必要な要素が欠如しています。"
note = "恐らく前方の文が不完全です"
[error.0004]
message = "定義文の無い修飾子"
label_0 = "定義文が必要です。この後に変数定義、関数定義もしくはデータ型定義を記述する必要があります"
note = "定義文を書く必要のない場合は削除してみてください"
[error.0005]
message = "代入文の記述形式が正しくありません"
label_0 = "右側の記述形式が正しくありません。"
[error.0006]
message = "交換文の記述形式が正しくありません"
label_0 = "右側の記述形式が正しくありません。"
[error.0007]
message = "インポート文の記述形式が正しくありません"
label_0 = ""
[error.0008]
message = "変数定義の記述形式が正しくありません"
label_0 = ""
[error.0009]
message = "関数定義の記述形式が正しくありません"
label_0 = ""
[error.0010]
message = "データ型定義の記述形式が正しくありません"
label_0 = ""
[error.0011]
message = "drop文の記述形式が正しくありません"
label_0 = ""
[error.0012]
message = "ブロックの括弧が閉じられていません"
label_0 = ""
[error.0013]
message = "計算式または論理式の記述形式が正しくありません"
label_0 = "式として有効ではありません。"
[error.0014]
message = "クロージャーの記述形式が正しくありません"
label_0 = ""
[error.0015]
message = "関数呼び出しの記述形式が正しくありません"
label_0 = ""
[error.0016]
message = "new式の記述形式が正しくありません"
label_0 = ""
[error.0017]
message = "if式の記述形式が正しくありません"
label_0 = ""
[error.0018]
message = "loop式の記述形式が正しくありません"
label_0 = ""
[error.0019]
message = "マッピング演算子の記述形式が正しくありません"
label_0 = ""
[error.0020]
message = "型指定の記述形式が正しくありません"
label_0 = ""
[error.0021]
message = "ジェネリクスの記述形式が正しくありません"
label_0 = ""
[error.0022]
message = "ジェネリクス定義の記述形式が正しくありません"
label_0 = ""
[error.0023]
message = "同じ名称の要素がすでに定義されています"
label_0 = "この名称は重複しています"
label_1 = "ここで既に定義されています"
note = "関数や型の定義名を重複させることはできません"
[error.0024]
message = "定義されていない識別子です"
label_0 = "この識別子が定義されていません"
note = "変数、関数や型の名前（識別子）はこの場所よりも前方で定義されているものでなければ使用できません"
[error.0025]
message = "代入対象の記述形式が正しくありません"
label_0 = "代入対象として有効ではありません"
note = "変数やフィールドを指す内容の記述が必要です"
[error.0026]
message = "データ型定義のブロック内に処理内容が直接記述されています"
label_0 = "この場所でこの文を記述することはできません"
label_1 = "データ型定義のブロック内です"
note = "この場所には任意の処理を行う内容を直接記述することはできません。関数定義を使用してください"
[error.0027]
message_single = "モジュール名'%0'に該当するソースコードが見つかりません"
message_double = "モジュール名'%0'もしくは'%1'に該当するソースコードが見つかりません"
label_0 = "このモジュールが見つかりません"
note = "記述に誤りがあるかライブラリを正しくインポートできていない可能性があります"
[error.0028]
message = "フィールドの型が明示されていません"
label_0 = "型を明示する必要があります"
[error.0029]
message = "static変数の型が明示されていません"
label_0 = "型を明示する必要があります"
[error.0030]
message = "モジュール'%0'内に'%1'が見つかりません"
label_0 = "この要素が見つかりません"
note = "正しくインポートできていないか定義されていない可能性があります"
[error.0031]
message = "ジェネリック要素を持たない型に対してジェネリック型が指定されています"
label_0 = "この型はジェネリック要素を持ちません"
label_1 = "この型指定は受け付けられません"
[error.0032]
message = "ジェネリック型の総数が一致しません"
label_0 = "この型にはジェネリック型要素が%0個必要です"
label_1 = "しかしここでは%1個指定されています"
[error.0033]
message = "型が正しく指定されていません"
label_0 = "これは型ではなく%0です"
label_1 = "ここで定義されています"
[error.0034]
message = "型が一致しません"
label_0 = "この型は %type です"
label_1 = "ここでジェネリック型変数%genericの型を指定しています : %type"
note = "ジェネリック型変数 %generics の型をそれぞれ一致させる必要があります"
[error.0035]
message = "変数をキャプチャできません"
label_0 = "ここでキャプチャしようとしています"
label_1 = "ここで定義されている要素をキャプチャしようとしています"
label_2 = "このスコープを超えてキャプチャできません"
[error.0036]
message = "new式の型が正しく指定されていません"
label_0 = "ここではclass型もしくはstruct型を指定する必要があります"
[error.0037]
message = "指定された要素が型 %0 の中から見つかりません"
label_0 = "この要素'%1'は型 %0 には存在しません"
note = "型 %0 の中に要素'%1'が定義されているかどうか確認してください"